version: '2'

volumes:
  mongo:
  postgres:

services:
    postgres:
      image: postgres
      restart: unless-stopped
      volumes:
        - postgres:/var/lib/postgresql/data
        - ./postgresinit.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

    mongo:
        image: mongo
        restart: unless-stopped
        volumes:
            - mongo:/data/db
            - ./mongoinit.js:/docker-entrypoint-initdb.d/init.js
        environment:
            - MONGO_INITDB_DATABASE=library 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root

    app:
        image: library:0.0.1-SNAPSHOT
        ports:
          - 8080:8080
        links:
          - mongo
          - postgres    
        restart: unless-stopped
        environment:
          - JAVA_OPTS="-Xmx512m"